### ISSUE TITLE
Иконки наезжают на заголовок в футере

### ISSUE THREAD

**Issue by ahmeditaev** [ahmeditaev/html_group_8_teamwork_team_3#13]
1. При разрешении в 320px иконки соц сетей наезжают на заголовок в футере http://c2n.me/3ImbJJi

2. Желательно чтобы было расстояние как минимум 5-10px между иконками и заголовком, а лучше будет если их переместить на следующую строку для удобства пользователей

3. Тикет будет закрыт только когда иконки перестанут прилипать к тексту

4. Время по плану на исправление этого бага - 15мин

Перед закрытием тикета указать в комментариях сколько ушло времени по факту!

**Comment by keylink** [comment]
fixed bag, time used for 10 min
