### ISSUE TITLE
Частичная сборка страницы + верстка блоков

### ISSUE THREAD

**Issue by ahmeditaev** [ahmeditaev/html_group_8_teamwork_team_3#15]
## Что нужно сделать ? 

- Добавить в разметку страницы 'footer' и 'header'

- Сверстать блок одной статьи

- Сверстать блок статьи с кнопкой

- Структура блоков должна быть похожа примерно как у контентных блоков в странице 'index.html'

- Если блоки будет похожи по структуре на предыдущие, то адаптивность прописывать не придется

## План выполнения

- Создать в проекте файл с названием 'mission.html'

- Добавить базовую разметку страницы

- Добавить в разметку элементы 'footer(a)' и 'header(a)'

- Сверстать указанные выше блоки

- Отступы между шапкой сайта и контентными блоками не указывать, т.к. при добавлении следующих блоков все уже указано в стилях.

- В стилях соблюдать логический порядок + добавить комментарий для своих блоков, если он отсутствует

## Зачем это нужно(мотивация)

- +100500 строк написания кода для Вашего же опыта

- Умение разбираться в чужом коде

- +1 шаг к желаемой зарплате в несколько тысяч $ 

## Критерий готовности

- Когда все пункты плана выполнения будут выполнены, можно будет считать что тикет сделан

## Время по плану

- Время по плану на верстку двух блоков 2.5ч

            После выполнения тикета указать сколько ушло времени по факту

**Comment by keylink** [comment]
затраченное время на блоки 1.5 или 2 часа примерно
