### ISSUE TITLE
Частичная сборка страницы + изменение контента в блоке новостей + добавление параграфа

### ISSUE THREAD

**Issue by ahmeditaev** [ahmeditaev/html_group_8_teamwork_team_3#16]
## Что нужно сделать ? 

- Добавить в разметку страницы блок со статьями и блок с цитатой

- Нарезать новые картинки и поменять их в блоке статей

- Структуру блоков без надобности не менять, так как нужно только изменить картинки в одном из блоков

- Указать в атрибутах 'img' натуральные размеры картинок (если правильно нарежете картинки то будет так 'width="254" height="94"' (дублировать в css не нужно, уже прописано для этих картинок)

- Добавить в 'row' новый класс 'col-md-12' и туда вставить нижеуказанный параграф

- Добавить параграф под блок с цитатой, положить текст в тэг 'p' с классом "description-quotes-block"

- При надобности указать отступы

- Если сделаете все правильно, то адаптивность прописывать не придется

## План выполнения

- Спуллить уже внесенные изменения

- Открыть страницу 'mission.html'

- Добавить в разметку уже готовые блоки: блок со статьями и блок с цитатой

- Нарезать картинки из макета 'mission.html'

- Заменить картинки с предыдущей страницы на новые только что нарезанные

- Указать атрибуты width и height 

- Сверстать вышеуказанный параграф

- В стилях соблюдать логический порядок, поэтому параграф стилизовать в месте где прописаны стили для цитатного блока

## Зачем это нужно(мотивация)

- +100500 строк написания кода для Вашего же опыта

- Умение разбираться в чужом коде

- +1 шаг к желаемой зарплате в несколько тысяч $ 

## Критерий готовности

- Когда все пункты плана выполнения будут выполнены, можно будет считать что тикет сделан

## Время по плану

- Время по плану два часа

            После выполнения тикета указать сколько ушло времени по факту

**Comment by janaratolonbaeva** [comment]
Добавить в разметку страницы блок со статьями и блок с цитатой ---- **сделано**

Нарезать новые картинки и поменять их в блоке статей ---- **сделано**

Структуру блоков без надобности не менять, так как нужно только изменить картинки в одном из блоков---- **выполнено, как указано**

Указать в атрибутах 'img' натуральные размеры картинок (если правильно нарежете картинки то будет так 'width="254" height="94"' (дублировать в css не нужно, уже прописано для этих картинок) ---- **после копирования в указании аттрибутов не было нужды, так как они были указаны, срезано как и указано**

Добавить в 'row' новый класс 'col-md-12' и туда вставить нижеуказанный параграф ---- **сделано**

Добавить параграф под блок с цитатой, положить текст в тэг 'p' с классом "description-quotes-block"---- **сделано**

При надобности указать отступы ---- **сделано, паддинги добавлены для тега**

Если сделаете все правильно, то адаптивность прописывать не придется---- **сделано, но еще не проверено**.

Время по факту:  30 мин.
