### ISSUE TITLE
Частичная сборка страницы + изменение контента в блоке новостей

### ISSUE THREAD

**Issue by ahmeditaev** [ahmeditaev/html_group_8_teamwork_team_3#17]
## Что нужно сделать ? 

- Добавить в разметку страницы блок со статьями

- Нарезать новые картинки и поменять их в блоке статей

- Структуру блоков без надобности не менять, так как нужно только изменить картинки в одном блоке

- Указать в атрибутах 'img' натуральные размеры картинок (если правильно нарежете картинки то будет так 'width="254" height="94"' (дублировать в css не нужно, уже прописано для этих картинок)

- Если сделаете все правильно, то адаптивность прописывать не придется

## План выполнения

- Спуллить уже внесенные изменения

- Открыть страницу 'hepl.html'

- Добавить в разметку уже готовый блок: блок со статьями

- Нарезать картинки из макета 'hepl.html'

- Заменить картинки с предыдущей страницы на новые только что нарезанные

## Зачем это нужно(мотивация)

- +100500 строк написания кода для Вашего же опыта

- Умение разбираться в чужом коде

- +1 шаг к желаемой зарплате в несколько тысяч $ 

## Критерий готовности

- Когда все пункты плана выполнения будут выполнены, можно будет считать что тикет сделан

## Время по плану

- Время по плану один час

            После выполнения тикета указать сколько ушло времени по факту

**Comment by janaratolonbaeva** [comment]
Добавить в разметку страницы блок со статьями ---- **сделано**

Нарезать новые картинки и поменять их в блоке статей ---- **сделано**

Структуру блоков без надобности не менять, так как нужно только изменить картинки в одном блоке ---- **сделано**

Указать в атрибутах 'img' натуральные размеры картинок (если правильно нарежете картинки то будет так 'width="254" height="94"' (дублировать в css не нужно, уже прописано для этих картинок) ---- **после копирования в указании атрибутов не было нужды, так как они были указаны, срезано как и указано**

Если сделаете все правильно, то адаптивность прописывать не придется ---- **сделано, но еще не проверено.**

Время по факту: 30 минут
