### ISSUE TITLE
Верстка страницы "Contact.html"

### ISSUE THREAD

**Issue by keylink** [ahmeditaev/html_group_8_teamwork_team_3#18]
# Верстка страницы 4й страницы "Contact.html" сайта Hope Center - исполнитель 'Ахмед'

## Задачи

1. Создать новый фаил Contact.html

2. Добавить в разметку страницы шапку и подвал сайта "Header & Footer"

3. Сверстать блок "Contact form", состоящий из блока формы и картинки.  <http://clip2net.com/s/3IsqRIO/>

4. Сверстаный блок должен быть пиксель перфект

5. Блок должен быть адаптивным.

***

### Ход выполнения заданий
***

1. Создать фаил "Contact.html".

2. Добавить разметку шапки и подвала сайта.

3. Сверстать блок с формой <http://clip2net.com/s/3IsqRIO/>

4. Структура блоков должна быть похожа примерно как у контентных блоков в странице 'index.html'

5. Стили прописывать в одном файле "style.css" в форматировании соблюдать порядок, не понятные участки кода комментировать

***

### Критерий готовности
***

Когда все пункты плана выполнения будут выполнены, можно будет считать что тикет сделан
Время по плану

Время по плану на верстку блока 1 ч.

      После выполнения тикета указать сколько ушло времени по факту

***

**Comment by ahmeditaev** [comment]
Создал блок с формой, без стилизации кнопок и без картинки

**Comment by ahmeditaev** [comment]
Тикет сделан. Затраченное время на выполнение этого тикета 1-1,5ч
