### ISSUE TITLE
Верстка страницы 4й страницы "Contact.html"

### ISSUE THREAD

**Issue by keylink** [ahmeditaev/html_group_8_teamwork_team_3#19]
# Верстка страницы 4й страницы "Contact.html" сайта Hope Center - исполнитель 'Жанара'

## Задачи

1. Добавить в разметку страницы новый блок "Our Address" <http://clip2net.com/s/3Iss0VR/>

2. Необходимые участки, закомментивать. 

3. Сверстаный блок должен быть пиксель перфект

4. Блок должен быть адаптивным.

***

### Ход выполнения заданий
***

1. Внести разметку блока в фаил "Contact.html"

2. Сверстать блок с формой <http://clip2net.com/s/3Iss0VR/>

3. Стили прописывать в одном файле "style.css" в форматировании соблюдать порядок, не понятные участки кода комментировать

***

### Критерий готовности
***

Когда все пункты плана выполнения будут выполнены, можно будет считать что тикет сделан
Время по плану

Время по плану на верстку блока 1.5 ч.

Время по факту на верстку блока 2 ч.

***

**Comment by janaratolonbaeva** [comment]
Работа выполнена, не уложилась во времени, больше времени ушло на бордер, думала как его привязать только к одному блоку, нашла решение: 
1) бордер задала блоку 
2) задала еще и бокс-шадоу.
