### ISSUE TITLE
Верстка страницы "About us"

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#22]
# Сверстать страницу "About us".

- **Сверстать страницу "About us":**

1. под мобайл-фест,
2. без макета PSD, дизайн командная работа (обсуждение в скайпе).
3. Перфект пиксель необязателен, но должен выглядить симметрично.
4. Фотокарточки нашей команды прикрепить на страницу.
5. Переход с этих фотокарточек на наши гитхабы.
6. Анимации и трансформации по ходу выполнения работы (идеи будем закидывать в скайп).

- **План выполнения:**

1. Сверстать страницу по макету, одобренному командой.
2. Постоянно связываться с командой для улучшения страницы.
3. Верстать мобайл-фест.

- **Критерий готовности:**

1. протестировать на кроссбраузерность Opera, Internet Explorer +10, Мozilla, Google Chrome, Netscape и Safari,
2. на расширениях минимум 320 пикселей и выше не должен появляться скролл,
3. проверка на валидность https://validator.w3.org/nu/#textarea http://csslint.net/#results

- **Время по плану:** не менее 6 часов и не более 10 часов.

_Время по факту: указать после окончания._

Исполнитель: **Канат.**

**Comment by keylink** [comment]
job done time used for - 7.5 hours
