### ISSUE TITLE
Хэдер 

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#3]
- Сверстать хэдер: 

1. под мобайл-фест, 
2. по макету PSD, попиксельно, скачать макет https://drive.google.com/drive/folders/0B_UCljvTCPnlejY4Y2RBcVhSekk
3. Перфект пиксель на расширениях 940пикселей и выше. 
4. Меню должно сворачиваться на расширениях 750-780 пикселях. 
5. Все меню должны быть внесены в меню-тоггл, скриншот http://prntscr.com/ehyi96.
6. Переход меню по страницам, ссылка должна переходить по страницам. 
7. Меню-тоггл должен быть доступен для пользователя, то есть не слишком маленького размера. 
8. Логотип должен быть вставлен картинкой. 

- План выполнения: 

1. Можно сверстать хэдер на бутстрапе. 
2. Верстать мобайл-фест, 

- Критерий готовности: 

1. протестировать на кроссбраузерность Opera, Internet Explorer +10, Мozilla, Google Chrome, Netscape и Safari, 
2. на расширениях минимум 320 пикселей и выше не должен появляться скролл, 
3. проверка на валидность   https://validator.w3.org/nu/#textarea     http://csslint.net/#results

- Время по плану: 3часа

- Время по факту:   **указать после окончания.**

**Comment by keylink** [comment]
сделал хедер, пофиксил баги, пиксель перфект
