### ISSUE TITLE
Промо-блок

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#4]
- Сверстать Промо-блок:

1. под мобайл-фест,
2. по макету PSD, попиксельно, скачать макет https://drive.google.com/drive/folders/0B_UCljvTCPnlejY4Y2RBcVhSekk
3. Перфект пиксель на расширениях 940пикселей и выше.
4. Табы должно быть сверху на мобильных устройствах и на планшетах, скриншот рисунка примера расположения табов http://prntscr.com/ehyu6o
5. Переход по табам - меняется картинка. 
6. Картинка может быть ссылкой, но не критично.

- План выполнения:

1. Можно сверстать промо на бутстрапе.
2. Верстать мобайл-фест,
3. Критерий готовности:
4. протестировать на кроссбраузерность Opera, Internet Explorer +10, Мozilla, Google Chrome, Netscape и Safari,
5. на расширениях минимум 320 пикселей и выше не должен появляться скролл,
6. проверка на валидность https://validator.w3.org/nu/#textarea http://csslint.net/#results

- Время по плану: 4 часа

- Время по факту: указать после окончания.

**Comment by ahmeditaev** [comment]
Сделал промо блок, ушло 5 часов, не учитывая корректировку шрифта
