### ISSUE TITLE
Блок с цитатой

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#6]
Сверстать блок с цитатой:
под мобайл-фест,
по макету PSD, попиксельно, скачать макет https://drive.google.com/drive/folders/0B_UCljvTCPnlejY4Y2RBcVhSekk
Перфект пиксель на расширениях 940 пикселей и выше.
Заголовок должен располагаться сверху цитаты на планшетах и мобильных устройствах.

План выполнения:
Можно сверстать блок с цитатой на бутстрапе.
Верстать мобайл-фест.
Критерий готовности:
протестировать на кроссбраузерность Opera, Internet Explorer +10, Мozilla, Google Chrome, Netscape и Safari,
на расширениях минимум 320 пикселей и выше не должен появляться скролл,
проверка на валидность https://validator.w3.org/nu/#textarea http://csslint.net/#results
Время по плану: 1 час

Время по факту: указать после окончания.

**Comment by ahmeditaev** [comment]
Сделал блок с цитатой, уложился в план, осталось исправить баг с кавычками
