### ISSUE TITLE
Блок статьи с заголовком даты

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#7]
- Сверстать Блок статьи с заголовком даты:

1. под мобайл-фест,
2. по макету PSD, попиксельно, скачать макет https://drive.google.com/drive/folders/0B_UCljvTCPnlejY4Y2RBcVhSekk
3. Перфект пиксель на расширениях 940 пикселей и выше.
4. Блоки должно располагаться один под другим на планшетах и мобильных устройствах.
5. Кнопка - ссылка.

- План выполнения:

1. Можно сверстать Блок статьи с заголовком даты на бутстрапе.
2. Верстать мобайл-фест.
 

- Критерий готовности:

4. протестировать на кроссбраузерность Opera, Internet Explorer +10, Мozilla, Google Chrome, Netscape и Safari,
5. на расширениях минимум 320 пикселей и выше не должен появляться скролл,
6. проверка на валидность https://validator.w3.org/nu/#textarea http://csslint.net/#results

- Время по плану: 1,5 часа

- Время по факту: указать после окончания.

**Comment by ahmeditaev** [comment]
Залил блок статьи с заголовком даты без бордеров
