### ISSUE TITLE
Размер шрифта на 320x слишком большой

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#8]
1. При расширении на мобильных устройствах размер шрифта слишком большой. Скриншот http://prntscr.com/ei542s
2. Можно и оставить, но корректней его не много уменьшить.
3. Сделать шрифт для заголовков меньше на пару пикселей (примерно).
4. Просмотреть на мобильных устройствах как выглядит, не занимает ли, много места на странице.

- Время по плану: 5 минут.

- Время по факту: указать после окончания работы.

**Comment by ahmeditaev** [comment]
Подкорректировал размер шрифта в промо блоке на всех разрешениях
