### ISSUE TITLE
Скролл на расширении 974 пикселей

### ISSUE THREAD

**Issue by janaratolonbaeva** [ahmeditaev/html_group_8_teamwork_team_3#9]
1. При ресайзинге на расширении 974 пикселей появляется скролл.
2. Появляется из-за марджинов в хэдере или паддингов в промо.
3. Не должно быть скролла от 320 пикселей и выше.
4. Обнулить паддинги или марджины или указать их в процентах.

- Время по плану: 1 час.
- Время по факту: указать после окончания работы.

**Comment by ahmeditaev** [comment]
Обнулил паддинги и марджины в проекте у блоков с классом "row" и "col-md-12". Скролла нет.
